% Specification for 1 pipe system (Approach 1 Optimized)
% Load the data from the Excel file
data = readtable('drive_cycle_final2.xlsx');
time = data.Time;      
rpm = data.RPM;        
torque = data.Torque_Nm; 

cooling = struct(...
    'n_tubes', 40, ...          % Realistic number of internal radiator tubes
    'w_tube', 0.002, ...        % Width of a single tube (2 mm)
    'w_radiator', 0.5, ...
    'h_tube', 0.020, ...        % Height of a single tube (20 mm)
    'L_tube', 0.8000, ...       % Length of radiator pass (0.8 m)
    'area_primary', 0.3000, ... % External radiator frontal area
    'area_fins', 2, ...         % External fin heat transfer area
    'fan_diameter', 0.4000, ...
    'fan_thickness', 0.0500, ...
    'cDrag', 2.5000, ...
    'denAir', 1.2000, ...
    'pumpArea', 0.000284, ...   % Perfectly matched to 19 mm pipe area
    'pipe1Length', 0.5000, ...
    'pipe1Dia', 0.019, ...      % 19 mm internal diameter
    'pipe2Length', 0.5000, ...
    'pipe2Dia', 0.019 ...       % 19 mm internal diameter
);